name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "release"
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: test
        run: |
          echo $(pwd)
          touch /tmp/testfile
          touch /testfile

      - name: exit
        run: exit 1

      - name: get repo name
        run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Get current year, month and day
        id: BUILD_DATE
        run: |
          echo "BUILD_DATE_YEAR=$(date -u +'%Y')" >> $GITHUB_ENV
          echo "BUILD_DATE_MONTH=$(date -u +'%m')" >> $GITHUB_ENV
          echo "BUILD_DATE_DAY=$(date -u +'%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_NUMBER=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_DOT=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
          echo "BUILD_DATE_WITH_HYPHEN=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Replace placeholders with current date
        run: |
          sed -i "s/version = \"dev\"/version = ${{ env.BUILD_DATE_WITH_DOT }}/g" ${{ env.REPO_NAME }}.lua
          sed -i "s/## Version: dev/## Version: ${{ env.BUILD_DATE_WITH_DOT }}/g" ${{ env.REPO_NAME }}.txt
          sed -i "s/## AddOnVersion: 00000000/## AddOnVersion: ${{ env.BUILD_DATE_NUMBER }}/g" ${{ env.REPO_NAME }}.txt

      - name: Create ZIP archive
        run: |
          mkdir -p /tmp/${{ env.REPO_NAME }}
          cp -r ./* /tmp/${{ env.REPO_NAME }}
          rm -rf /tmp/${{ env.REPO_NAME }}/{.git,.github,.gitignore}
          zip -r "${{ env.REPO_NAME }}-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip" /tmp/${{ env.REPO_NAME }} -x "*.git*" "*.github*" ".gitignore"

      - name: Create GitHub Release
        #id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ env.REPO_NAME }} Release - ${{ env.BUILD_DATE_WITH_DOT }}"
          commit: ${{ github.ref }}
          tag: "${{ env.BUILD_DATE_WITH_DOT }}"
          artifacts: "${{ env.REPO_NAME }}-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip"
          artifactContentType: application/zip
          bodyFile: CHANGELOG.md
          allowUpdates: true
          makeLatest: true

      - name: Send to ESOUI
        env:
          ESOUI_API_KEY: ${{ secrets.ESOUI_API_KEY }}
          ADDON_ID: 3998
        run: |
          curl -X POST \
            -H "x-api-token: $ESOUI_API_KEY" \
            -F "id=${ADDON_ID}" \
            -F "version=${{ env.BUILD_DATE_WITH_DOT }}" \
            -F "updatefile=@${{ env.REPO_NAME }}-${{ env.BUILD_DATE_WITH_HYPHEN }}.zip" \
            -F "changelog=$(cat CHANGELOG.md)" \
            https://api.esoui.com/addons/update